language: node_js

node_js:
  - 13

services:
  - docker

install:
  - echo "install step"

before_script:
  - echo "Starting..."

script:
  - docker --version
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  ## Tagging
  - docker tag udagram-reverseproxy devopnguyenan88/udagram-reverseproxy:v1
  - docker tag udagram-api-feed devopnguyenan88/udagram-api-feed:v1
  - docker tag udagram-api-user devopnguyenan88/udagram-api-user:v1
  - docker tag udagram-frontend devopnguyenan88/udagram-frontend:local
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push devopnguyenan88/udagram-reverseproxy:v1
  - docker push devopnguyenan88/udagram-api-feed:v1
  - docker push devopnguyenan88/udagram-api-user:v1
  - docker push devopnguyenan88/udagram-frontend:local